name: Knode proxy

on: [push]

env:
  GIT_REF: ${{ github.head_ref || github.ref_name }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_URL }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run tests
        run: >
          KNODE_CFG='{"nodes":{"ethereum": ["https://rpc.ankr.com/eth"]}}' PYTHONPATH=.  pytest tests/

  docker:
    runs-on: self-hosted
    needs: Test
    steps:
      - uses: actions/checkout@v4

      - name: Build and push
        run: ./.github/scripts/build_and_push.sh
        env:
          DOCKER_IMAGE_NAME: "registry.digitalocean.com/karpatkey/knode-proxy"
          DOCKERFILE: "./Dockerfile"
